# Generated by Django 3.2.7 on 2022-02-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='count',
            field=models.IntegerField(default=10),
        ),
    ]
