# Generated by Django 3.2.7 on 2022-02-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iw', '0002_facility_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.CharField(max_length=4000),
        ),
    ]
