# Generated by Django 3.2.7 on 2022-02-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iw', '0003_alter_facility_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('filename', models.CharField(max_length=30)),
            ],
        ),
    ]
