# Generated by Django 3.2.7 on 2022-02-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iw', '0004_historicdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicdata',
            name='title',
            field=models.CharField(default='no name', max_length=30),
        ),
    ]
