# Generated by Django 3.2.7 on 2022-02-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iw', '0004_historicdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('init', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='historicdata',
            name='title',
            field=models.CharField(default='no name', max_length=30),
        ),
    ]
