# Generated by Django 3.2.7 on 2022-02-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iw', '0005_auto_20220206_0023'),
        ('iw', '0005_historicdata_title'),
    ]

    operations = [
    ]
