# Generated by Django 3.2.7 on 2022-02-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iw', '0007_auto_20220208_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='color_b',
            field=models.IntegerField(default=255),
        ),
        migrations.AddField(
            model_name='facility',
            name='color_g',
            field=models.IntegerField(default=255),
        ),
        migrations.AddField(
            model_name='facility',
            name='color_r',
            field=models.IntegerField(default=255),
        ),
        migrations.AlterField(
            model_name='facility',
            name='manufacturer',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mainsys',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='subsys',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
