# Generated by Django 3.2.7 on 2022-02-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iw', '0008_auto_20220210_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsys',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
